# The main routing configuration file that defines 
# load balancing rules, reverse proxy paths, and traffic rules.

# global Setting
user nginx;
worker_processes auto;

# event block
events {
    worker_connections 1024; # how many connections worker can handle
}

# the HTTP block
http {
    # optimisation
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Performance optimizations
    sendfile on;
    keepalive_timeout 65;
    gzip on;

    # defining our backend upstream container
    upstream backend_servers { 
        server web-app:3000;
        # Docker's internal DNS lets us use the service name 'web-app'
    }

    # server block
    server { 
        listen 80;
        server_name localhost;

    # location block
        location / { 
            # guide proxy traffic to Express App
            proxy_pass http://backend_servers;

            # important Headers, Express know where traffic comes from
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}